# Generated by Django 4.0.6 on 2022-07-24 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reoccuringapp',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='reoccuringapp',
            name='time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '8:00 AM'), (datetime.time(12, 15), '12:15 PM'), (datetime.time(14, 30), '2:30 PM')], default=datetime.time(8, 0)),
        ),
    ]
