# Generated by Django 4.0.6 on 2022-07-24 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reoccuringapp_day_alter_reoccuringapp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reoccuringapp',
            name='time',
            field=models.TimeField(choices=[(datetime.time(10, 0), '10:00 AM'), (datetime.time(12, 15), '12:15 PM'), (datetime.time(14, 30), '2:30 PM')], default=datetime.time(8, 0)),
        ),
    ]
