# Generated by Django 4.0.6 on 2022-07-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='availability',
            field=models.ManyToManyField(to='api.availability'),
        ),
    ]
