# Generated by Django 4.0.6 on 2022-07-24 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_availability_teacher_teacher_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=10)),
                ('start_time', models.TimeField(choices=[(datetime.time(10, 0), '10:00 AM'), (datetime.time(12, 15), '12:15 PM'), (datetime.time(14, 30), '2:30 PM')])),
                ('end_time', models.TimeField(choices=[(datetime.time(11, 50), '12:00 PM'), (datetime.time(2, 15), '2:15 PM'), (datetime.time(4, 30), '4:30 PM')])),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.ManyToManyField(to='api.timeslot'),
        ),
    ]
