# Generated by Django 4.0.6 on 2022-07-24 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timeslot_delete_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='status',
            field=models.CharField(blank=True, default='unconfirmed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(choices=[(datetime.time(12, 0), '12:00 PM'), (datetime.time(2, 15), '2:15 PM'), (datetime.time(16, 30), '4:30 PM')]),
        ),
    ]
