# Generated by Django 4.0.6 on 2022-07-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appinstance_status_alter_timeslot_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinstance',
            options={'ordering': ['student', 'date', 'time']},
        ),
    ]
