# Generated by Django 4.0.6 on 2022-07-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appinstance_date_alter_appinstance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reoccuringapp',
            name='time',
        ),
        migrations.AddField(
            model_name='reoccuringapp',
            name='time',
            field=models.ManyToManyField(to='api.timeslot'),
        ),
    ]
